### ISSUE TITLE
Invisible Corpses (Hidden By Spike Traps)

### ISSUE THREAD

**Issue by Liham** [AI-Productions/AndOre#195]
Description: If someone who is not part of your corp dies on one of your spike traps, the corpse will be invisible. Walking on the spike trap is impossible when then is a corpse on it.  If you are unaware some one died on the spike trap you will think that, for some reason, you can't walk over your own spike trap because you can't see the corpse.
Here are pictures of me not being able to step on the trap, and standing on it after looting the corpse:
![capture](https://cloud.githubusercontent.com/assets/22137914/18999423/7ded34f4-870b-11e6-9d3a-a6cb33c91f46.PNG)
![capture](https://cloud.githubusercontent.com/assets/22137914/18999425/81040406-870b-11e6-9359-c0b82d319a60.jpeg)

Possible solution: Make loot transparent like players, so you can see it on top of spike traps.

Replication: Have someone who is not in your corp die on one of your spike traps, and then try and walk on the spike trap.

Date: 9/30/16

**Comment by JCharante** [comment]
@halstedlarsson I think a possible fix would be first, moving the corpse in front of the render queue so it shows up above the spiketrap, and also making it so if you die on a corp owned building, the owner of the building autoloots the loot.

**Comment by JCharante** [comment]
I'm working on it.

**Comment by JCharante** [comment]
Fixed in https://github.com/AI-Productions/AndOre/commit/19571544569f8ed61c49d4512162cf75e6116e1a
